Feat cdc python
hoihu/micropython-lib pull request #1
Opened 2023-07-28 20:54 UTC by linted

Fixed an major error in the _CS_DESC_TYPE message being sent by the CDCControlInterface. Changed to take advantage of the ring buffer found in the midi interface to implement a better read cache mechanism.

2023-09-03 10:24 UTC, hoihu commented
Hi @linted 

I'm sorry to come back late, I did not see your PR. Thanks a lot for the feedback. I guess we have corrected bugs in parallel....

I've updated my branch since (you might have seen that) and corrected some of the bugs that you also have noticed. I just now added support for set_line_coding and set_control_line so you might have a look if that beneficial for you too? 

Regarding the ring buffer, I settled for just creating a bytearray each time `read` is called. That's horribly memory inefficent and needs to be addressed for sure. At least now it should read-in all available data from the endpoints (this wasn't the case before, as you may have figured out too)

Maybe I've overseen some of the issues you've pointed out. Would you mind to comment on the PR https://github.com/projectgus/micropython-lib/pull/2 ? I think that's better since @projectgus can also share his view.

2023-09-03 12:49 UTC, hoihu requested changes
There are a few bugs solved in the PR, thanks! 

I can correct those obvious ones with reference to you. Otherwise, would be good to split the ringbuffer addition from the rest and place a separate PR.

2023-09-03 12:49 UTC, hoihu commented on micropython/usbd/cdc.py
> +                            _CDC_ITF_CONTROL_PROT, 4)  # "IAD"
As I understand, this is an index to a string descriptor describing the function. Do we have a string descriptor for that? Otherwise this value is 0.

2023-09-03 12:49 UTC, hoihu commented on micropython/usbd/cdc.py
> +        desc += ustruct.pack("<BBBBB", 5, _CS_DESC_TYPE, 6, itf_idx, itf_idx+1)  # "Union"
right, I corrected the `itf_idx+1` already, but missed the struct pack pattern.

2023-09-03 12:49 UTC, hoihu commented on micropython/usbd/cdc.py
> +        self.submit_xfer(self.ep_in, data)
looks good

2023-09-03 12:49 UTC, hoihu commented on micropython/usbd/cdc.py
> +
I'm not sure about this one. As I recall, the CDC spec specifically asked for two endpoints for the data interface. So in my latest version it looks like
```
        self.ep_in = (ep_addr + 1) | EP_IN_FLAG
        self.ep_out = (ep_addr + 2)
```

2023-09-03 12:49 UTC, hoihu commented on micropython/usbd/cdc.py
> +        return (desc, [], (self.ep_in,))
Yes that looks good

2023-09-05 01:23 UTC, projectgus commented
Thanks @linted for the PR and @hoihu for the heads-up.

I confess that I have my own version of this branch as a WIP as well. It has some of the same fixes, plus some deeper changes to support using the CDC as a Python stream. :facepalm: That's my fault for not being more proactive about pushing it, sorry.

I'll go over these changes and see if there's anything that applies to the branch I have, but hopefully push that today or tomorrow so you can both take a look, too.

2023-09-05 05:05 UTC, hoihu commented
@projectgus  all good - I havent looked too much into supporting stream interfaces. Looking forward to the new stuff!

and yeah ChatGPT advices have to be taken with a grain of salt 😀. But to defend „him“ I actually got some decent advice when asking USB low level staff. I might have to check wireshark then for the serial_state support

2023-09-07 04:51 UTC, projectgus commented
I've pushed where I'm up to, here: https://github.com/projectgus/micropython-lib/tree/feature/usbd_python_cdc

Although this still doesn't really work. Most of the effort I've been spending to find a memory-efficient way to buffer read and write operations to USB. I have something but I'm still not particularly happy with it.

2023-09-10 16:31 UTC, linted commented on micropython/usbd/cdc.py
> +        desc += ustruct.pack("<BBBBB", 5, _CS_DESC_TYPE, 6, itf_idx, itf_idx+1)  # "Union"
This was the big problem that fixed most things. It took me a while to realize it as well.

2023-09-10 16:32 UTC, linted commented on micropython/usbd/cdc.py
> +                            _CDC_ITF_CONTROL_PROT, 4)  # "IAD"
I honestly don't remember why I made it 4, just that it worked.

2023-09-10 16:34 UTC, linted commented
Since there has been significant work on other branches, I don't think this PR needs to remain open. I'll go ahead and close it.

2023-09-10 16:34 UTC, closed without merging